// Curated list of common Indian colleges for the interest-form autocomplete.
// Coverage focus: IITs, NITs, IIITs, IIMs, AIIMS + state-university engineering colleges
// across Tamil Nadu, Telangana/AP, Karnataka, Maharashtra, Delhi NCR, UP, Kerala, etc.
// Add to this list as gaps become apparent. The free-text input is the fallback for anything missing.

export const INDIAN_COLLEGES: string[] = [
  // IITs
  'Indian Institute of Technology Bombay',
  'Indian Institute of Technology Delhi',
  'Indian Institute of Technology Madras',
  'Indian Institute of Technology Kanpur',
  'Indian Institute of Technology Kharagpur',
  'Indian Institute of Technology Roorkee',
  'Indian Institute of Technology Guwahati',
  'Indian Institute of Technology Hyderabad',
  'Indian Institute of Technology Indore',
  'Indian Institute of Technology (BHU) Varanasi',
  'Indian Institute of Technology Gandhinagar',
  'Indian Institute of Technology Patna',
  'Indian Institute of Technology Ropar',
  'Indian Institute of Technology Bhubaneswar',
  'Indian Institute of Technology Mandi',
  'Indian Institute of Technology Jodhpur',
  'Indian Institute of Technology Tirupati',
  'Indian Institute of Technology Palakkad',
  'Indian Institute of Technology Bhilai',
  'Indian Institute of Technology Goa',
  'Indian Institute of Technology Jammu',
  'Indian Institute of Technology Dharwad',
  'Indian Institute of Technology (ISM) Dhanbad',

  // NITs
  'National Institute of Technology Tiruchirappalli',
  'National Institute of Technology Karnataka, Surathkal',
  'National Institute of Technology Warangal',
  'National Institute of Technology Rourkela',
  'National Institute of Technology Calicut',
  'Motilal Nehru National Institute of Technology Allahabad',
  'Visvesvaraya National Institute of Technology Nagpur',
  'Maulana Azad National Institute of Technology Bhopal',
  'Malaviya National Institute of Technology Jaipur',
  'National Institute of Technology Kurukshetra',
  'National Institute of Technology Durgapur',
  'National Institute of Technology Silchar',
  'Sardar Vallabhbhai National Institute of Technology Surat',
  'National Institute of Technology Hamirpur',
  'National Institute of Technology Jamshedpur',
  'National Institute of Technology Raipur',
  'Dr. B. R. Ambedkar National Institute of Technology Jalandhar',
  'National Institute of Technology Patna',
  'National Institute of Technology Srinagar',
  'National Institute of Technology Agartala',
  'National Institute of Technology Goa',
  'National Institute of Technology Manipur',
  'National Institute of Technology Meghalaya',
  'National Institute of Technology Mizoram',
  'National Institute of Technology Nagaland',
  'National Institute of Technology Puducherry',
  'National Institute of Technology Sikkim',
  'National Institute of Technology Andhra Pradesh',
  'National Institute of Technology Uttarakhand',
  'National Institute of Technology Arunachal Pradesh',
  'National Institute of Technology Delhi',

  // IIITs
  'International Institute of Information Technology Hyderabad',
  'International Institute of Information Technology Bangalore',
  'Indian Institute of Information Technology Allahabad',
  'Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior',
  'Indian Institute of Information Technology Design and Manufacturing Jabalpur',
  'Indian Institute of Information Technology Design and Manufacturing Kancheepuram',
  'Indian Institute of Information Technology Guwahati',
  'Indian Institute of Information Technology Vadodara',
  'Indian Institute of Information Technology Kota',
  'Indian Institute of Information Technology Tiruchirappalli',
  'Indian Institute of Information Technology Una',
  'Indian Institute of Information Technology Sri City',
  'Indian Institute of Information Technology Lucknow',
  'Indian Institute of Information Technology Kalyani',
  'Indian Institute of Information Technology Nagpur',
  'Indian Institute of Information Technology Sonepat',
  'Indian Institute of Information Technology Pune',
  'Indian Institute of Information Technology Surat',
  'Indian Institute of Information Technology Bhopal',
  'Indian Institute of Information Technology Bhagalpur',
  'Indian Institute of Information Technology Agartala',
  'Indian Institute of Information Technology Manipur',
  'Indian Institute of Information Technology Kottayam',
  'Indian Institute of Information Technology Dharwad',
  'Indian Institute of Information Technology Raichur',
  'Indian Institute of Information Technology Ranchi',
  'Indian Institute of Information Technology Senapati, Manipur',
  'Indian Institute of Information Technology Kurnool',

  // IIMs
  'Indian Institute of Management Ahmedabad',
  'Indian Institute of Management Bangalore',
  'Indian Institute of Management Calcutta',
  'Indian Institute of Management Lucknow',
  'Indian Institute of Management Kozhikode',
  'Indian Institute of Management Indore',
  'Indian Institute of Management Shillong',
  'Indian Institute of Management Rohtak',
  'Indian Institute of Management Ranchi',
  'Indian Institute of Management Raipur',
  'Indian Institute of Management Tiruchirappalli',
  'Indian Institute of Management Udaipur',
  'Indian Institute of Management Kashipur',
  'Indian Institute of Management Nagpur',
  'Indian Institute of Management Amritsar',
  'Indian Institute of Management Bodh Gaya',
  'Indian Institute of Management Sambalpur',
  'Indian Institute of Management Sirmaur',
  'Indian Institute of Management Visakhapatnam',
  'Indian Institute of Management Jammu',

  // AIIMS
  'All India Institute of Medical Sciences Delhi',
  'All India Institute of Medical Sciences Bhopal',
  'All India Institute of Medical Sciences Bhubaneswar',
  'All India Institute of Medical Sciences Jodhpur',
  'All India Institute of Medical Sciences Patna',
  'All India Institute of Medical Sciences Raipur',
  'All India Institute of Medical Sciences Rishikesh',
  'All India Institute of Medical Sciences Nagpur',
  'All India Institute of Medical Sciences Mangalagiri',
  'All India Institute of Medical Sciences Kalyani',
  'All India Institute of Medical Sciences Bibinagar',
  'All India Institute of Medical Sciences Gorakhpur',
  'All India Institute of Medical Sciences Rae Bareli',
  'All India Institute of Medical Sciences Madurai',

  // IISc / IISERs
  'Indian Institute of Science, Bangalore',
  'Indian Institute of Science Education and Research Pune',
  'Indian Institute of Science Education and Research Kolkata',
  'Indian Institute of Science Education and Research Mohali',
  'Indian Institute of Science Education and Research Bhopal',
  'Indian Institute of Science Education and Research Thiruvananthapuram',
  'Indian Institute of Science Education and Research Tirupati',
  'Indian Institute of Science Education and Research Berhampur',

  // BITS, VIT, SRM, Manipal, Amrita, Thapar, Christ, etc.
  'Birla Institute of Technology and Science, Pilani',
  'Birla Institute of Technology and Science, Pilani — Hyderabad Campus',
  'Birla Institute of Technology and Science, Pilani — Goa Campus',
  'Birla Institute of Technology and Science, Pilani — Dubai Campus',
  'Birla Institute of Technology, Mesra',
  'Vellore Institute of Technology, Vellore',
  'Vellore Institute of Technology, Chennai',
  'Vellore Institute of Technology, Amaravati',
  'Vellore Institute of Technology, Bhopal',
  'SRM Institute of Science and Technology, Kattankulathur',
  'SRM Institute of Science and Technology, Ramapuram',
  'SRM University, AP',
  'SRM University Sonepat',
  'Manipal Institute of Technology, Manipal',
  'Manipal Academy of Higher Education, Manipal',
  'Amrita Vishwa Vidyapeetham, Coimbatore',
  'Amrita Vishwa Vidyapeetham, Bengaluru',
  'Amrita Vishwa Vidyapeetham, Amritapuri',
  'Amrita Vishwa Vidyapeetham, Chennai',
  'Thapar Institute of Engineering and Technology, Patiala',
  'Christ University, Bangalore',
  'Symbiosis Institute of Technology, Pune',
  'Symbiosis International University, Pune',
  'Lovely Professional University, Phagwara',
  'Chandigarh University, Mohali',
  'Shiv Nadar University, Greater Noida',
  'Ashoka University, Sonepat',
  'O.P. Jindal Global University, Sonepat',
  'Plaksha University, Mohali',
  'KIIT University, Bhubaneswar',
  'Sastra Deemed University, Thanjavur',
  'PES University, Bangalore',
  'RV College of Engineering, Bangalore',
  'BMS College of Engineering, Bangalore',
  'Dayananda Sagar College of Engineering, Bangalore',
  'MS Ramaiah Institute of Technology, Bangalore',
  'Christ University Engineering, Bangalore',
  'Reva University, Bangalore',
  'Jain University, Bangalore',
  'New Horizon College of Engineering, Bangalore',
  'Nitte Meenakshi Institute of Technology, Bangalore',

  // Tamil Nadu — Anna University constituent + popular affiliated
  'Anna University, Chennai',
  'College of Engineering, Guindy (CEG), Anna University',
  'Madras Institute of Technology (MIT), Anna University',
  'Alagappa College of Technology, Anna University',
  'PSG College of Technology, Coimbatore',
  'Government College of Technology, Coimbatore',
  'Coimbatore Institute of Technology',
  'Kumaraguru College of Technology, Coimbatore',
  'Karpagam College of Engineering, Coimbatore',
  'Sri Krishna College of Engineering and Technology, Coimbatore',
  'Sri Krishna College of Technology, Coimbatore',
  'Sri Shakti Institute of Engineering and Technology, Coimbatore',
  'Bannari Amman Institute of Technology, Sathyamangalam',
  'Kongu Engineering College, Erode',
  'Velammal Engineering College, Chennai',
  'Velammal Institute of Technology, Chennai',
  'SSN College of Engineering, Chennai',
  'Sri Sairam Engineering College, Chennai',
  'Rajalakshmi Engineering College, Chennai',
  'Easwari Engineering College, Chennai',
  'St. Joseph’s College of Engineering, Chennai',
  'R.M.K. Engineering College, Chennai',
  'Saveetha Engineering College, Chennai',
  'Hindustan Institute of Technology and Science, Chennai',
  'Sathyabama Institute of Science and Technology, Chennai',
  'Vel Tech University, Chennai',
  'Karunya Institute of Technology and Sciences, Coimbatore',
  'Mepco Schlenk Engineering College, Sivakasi',
  'National Engineering College, Kovilpatti',
  'Thiagarajar College of Engineering, Madurai',
  'K.L.N. College of Engineering, Madurai',
  'Madurai Kamaraj University',
  'Bharathidasan University, Tiruchirappalli',
  'Bharathiar University, Coimbatore',
  'University of Madras',
  'Loyola College, Chennai',
  'Madras Christian College, Chennai',
  'Stella Maris College, Chennai',
  'Women’s Christian College, Chennai',
  'Presidency College, Chennai',

  // Telangana / Andhra Pradesh
  'Jawaharlal Nehru Technological University, Hyderabad',
  'Jawaharlal Nehru Technological University, Kakinada',
  'Jawaharlal Nehru Technological University, Anantapur',
  'Osmania University, Hyderabad',
  'Andhra University, Visakhapatnam',
  'Sri Venkateswara University, Tirupati',
  'University of Hyderabad',
  'Chaitanya Bharathi Institute of Technology, Hyderabad',
  'Vasavi College of Engineering, Hyderabad',
  'CVR College of Engineering, Hyderabad',
  'Vardhaman College of Engineering, Hyderabad',
  'CMR College of Engineering and Technology, Hyderabad',
  'GRIET (Gokaraju Rangaraju Institute of Engineering and Technology), Hyderabad',
  'Mahindra University, Hyderabad',
  'Woxsen University, Hyderabad',
  'GITAM University, Visakhapatnam',
  'KL University, Vijayawada',
  'Vignan’s Foundation for Science Technology and Research, Guntur',

  // Karnataka — VTU affiliated + state universities
  'Visvesvaraya Technological University, Belagavi',
  'Bangalore University',
  'Mangalore University',
  'University of Mysore',
  'Karnataka State Open University',
  'BNM Institute of Technology, Bangalore',
  'JSS Science and Technology University, Mysuru',
  'NMAM Institute of Technology, Nitte',
  'Sahyadri College of Engineering and Management, Mangalore',

  // Maharashtra
  'College of Engineering, Pune (COEP)',
  'Veermata Jijabai Technological Institute (VJTI), Mumbai',
  'Sardar Patel Institute of Technology, Mumbai',
  'Institute of Chemical Technology, Mumbai',
  'K. J. Somaiya College of Engineering, Mumbai',
  'Dwarkadas J. Sanghvi College of Engineering, Mumbai',
  'Thadomal Shahani Engineering College, Mumbai',
  'Sardar Patel College of Engineering, Mumbai',
  'Pune Institute of Computer Technology (PICT), Pune',
  'Vishwakarma Institute of Technology, Pune',
  'MIT World Peace University, Pune',
  'Walchand College of Engineering, Sangli',
  'University of Mumbai',
  'Savitribai Phule Pune University',
  'Mumbai University Institute of Chemical Technology',

  // Delhi NCR
  'University of Delhi',
  'Delhi Technological University (DTU)',
  'Netaji Subhas University of Technology (NSUT)',
  'Indraprastha Institute of Information Technology, Delhi (IIIT-Delhi)',
  'Guru Gobind Singh Indraprastha University (GGSIPU), Delhi',
  'Jawaharlal Nehru University, Delhi',
  'Jamia Millia Islamia, Delhi',
  'Jamia Hamdard, Delhi',
  'Hindu College, University of Delhi',
  'St. Stephen’s College, Delhi',
  'Lady Shri Ram College, Delhi',
  'Miranda House, Delhi',
  'Hansraj College, Delhi',
  'Kirori Mal College, Delhi',
  'Ramjas College, Delhi',
  'Shri Ram College of Commerce, Delhi',

  // UP, MP, Bihar, Jharkhand
  'Aligarh Muslim University',
  'Banaras Hindu University',
  'Allahabad University',
  'Lucknow University',
  'Harcourt Butler Technical University, Kanpur',
  'Madan Mohan Malaviya University of Technology, Gorakhpur',
  'Babu Banarasi Das University, Lucknow',
  'Galgotias University, Greater Noida',
  'Bennett University, Greater Noida',
  'Amity University, Noida',
  'KIET Group of Institutions, Ghaziabad',
  'JSS Academy of Technical Education, Noida',
  'Devi Ahilya Vishwavidyalaya, Indore',
  'Maulana Azad National Institute of Technology, Bhopal',
  'Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal',
  'Patna University',
  'Nalanda Open University, Patna',
  'Chanakya National Law University, Patna',
  'Birla Institute of Technology, Patna',

  // West Bengal
  'Jadavpur University, Kolkata',
  'University of Calcutta',
  'Indian Statistical Institute, Kolkata',
  'Heritage Institute of Technology, Kolkata',
  'Institute of Engineering and Management, Kolkata',
  'Maulana Abul Kalam Azad University of Technology, West Bengal',
  'Presidency University, Kolkata',
  'St. Xavier’s College, Kolkata',

  // Kerala
  'College of Engineering, Trivandrum',
  'TKM College of Engineering, Kollam',
  'Government Engineering College, Thrissur',
  'Government Engineering College, Barton Hill',
  'Mar Athanasius College of Engineering, Kothamangalam',
  'Rajiv Gandhi Institute of Technology, Kottayam',
  'Cochin University of Science and Technology (CUSAT)',
  'University of Kerala, Thiruvananthapuram',
  'Mahatma Gandhi University, Kottayam',
  'Calicut University',
  'APJ Abdul Kalam Technological University, Thiruvananthapuram',

  // Odisha
  'Veer Surendra Sai University of Technology, Burla',
  'International Institute of Information Technology, Bhubaneswar',
  'C.V. Raman Global University, Bhubaneswar',
  'Siksha O Anusandhan University, Bhubaneswar',
  'Utkal University, Bhubaneswar',

  // Punjab / Haryana
  'Punjab Engineering College, Chandigarh',
  'Punjabi University, Patiala',
  'Guru Nanak Dev University, Amritsar',
  'Panjab University, Chandigarh',
  'Maharishi Markandeshwar University, Mullana',
  'Deenbandhu Chhotu Ram University of Science and Technology, Murthal',
  'YMCA University of Science and Technology, Faridabad',
  'Manav Rachna International Institute of Research and Studies, Faridabad',
  'Kurukshetra University',
  'Maharshi Dayanand University, Rohtak',

  // Rajasthan
  'Malaviya National Institute of Technology Jaipur',
  'Manipal University Jaipur',
  'Banasthali Vidyapith',
  'JECRC University, Jaipur',
  'University of Rajasthan, Jaipur',
  'Mody University of Science and Technology, Sikar',

  // Gujarat
  'Sardar Vallabhbhai National Institute of Technology, Surat',
  'Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT), Gandhinagar',
  'Pandit Deendayal Energy University, Gandhinagar',
  'Nirma University, Ahmedabad',
  'Gujarat Technological University, Ahmedabad',
  'L. D. College of Engineering, Ahmedabad',
  'M. S. University of Baroda, Vadodara',
  'Charotar University of Science and Technology (CHARUSAT), Anand',

  // North East
  'Tezpur University',
  'Gauhati University',
  'Assam University, Silchar',
  'Manipur University',
  'Mizoram University',
  'Sikkim University',

  // Catch-all option for free text fallback
  'Other / Not listed',
]
